# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20201021_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '售罄'), (1, '上线'), (0, '下架')], default=1, verbose_name='商品状态'),
        ),
    ]
