# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='成都市新都区西南石油大学', max_length=100, verbose_name='地址'),
        ),
    ]
